stages:
  - build
  - test
  - push
  - deploy
  - build_weekly
  - build_monthly

initial_testing:
  stage: test
  tags:
    - aquarius
  script:
    - python -V  # Print out python version for debugging
    - echo "$0"
    - echo "$USER"
    - echo $HOSTNAME
    - source ~/.bashrc
    - python_conda -c "print('Bubu was here\n'*5)"
    - snakemake --help

job:on-schedule:
  only:
    - schedules
  tags:
    - aquarius
  script:
    - python_conda -c "print('scheduled job here, nothing to see')"
  
