stages:
  - build
  - test
  - push
  - deploy
  - build_weekly
  - build_monthly

variables:
  PYTHON: "/home/gitlab-runner/anaconda3/envs/snake/bin/python"
  SNAKEMAKE: "/home/gitlab-runner/anaconda3/envs/snake/bin/snakemake"


initial_testing:
  stage: test
  tags:
    - aquarius
  script:
    - echo "$(date)"
    - python -V  # Print out python version for debugging
    - echo "$0"
    - echo "$USER"
    - echo $HOSTNAME
    - source ~/.bashrc
    - /home/gitlab-runner/anaconda3/envs/snake/bin/python -c "print('Bubu was here\n'*5)"
    - SNAKEMAKE --help

job:on-schedule:
  only:
    - schedules
  tags:
    - aquarius
  script:
    - python_conda -c "print('scheduled job here, nothing to see')"
  
