stages:
  - test

variables:
  PYTHON: "/home/gitlab-runner/anaconda3/envs/snake/bin/python"
  SNAKEMAKE: "/home/gitlab-runner/anaconda3/envs/snake/bin/snakemake"
  PYTEST: "/home/dblyon/anaconda3/envs/agotool/bin/pytest"

before_script:
    - export DATE=$(date +"%Y_%m_%d_%I_%M_%p")    
    - export TAR_FILE_NAME="bak_aGOtool_flatfiles_$DATE.tar"

test:
  stage: test
  tags:
    - pisces
  script:
    - echo "$(date)"
    - echo $DATE
    - $PYTHON -V
    - $SNAKEMAKE --version
    - $PYTEST --version
    - echo "$USER"
    - echo $HOSTNAME    
    - echo $TAR_FILE_NAME
  
    ## PyTest
    - cd /home/dblyon/agotool/app/python/testing/sanity
    - /home/dblyon/anaconda3/envs/agotool/bin/pytest
