version: '3'
services:
  db: # name
    image: "postgres:10"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
       #- "agotool_data:/agotool_data" # version 1
      - .:/agotool_data # version 2, bind mount to mount files from the host to the container
#    ports: # expose port in order to connect to PostgreSQL
#      - "5432:5432"
    env_file:
      - ./app/env_file
    networks:
      - db_nw

  flaskapp:
    image: "agotool"
    restart: unless-stopped
    build: . # uncomment to build from Dockerfile, else pull from dockerhub
    volumes:
      - ./app/:/opt/services/flaskapp/src
      #- "agotool_data:/agotool_data" # version 1
      - .:/agotool_data # version 2, # bind mounted volume from host, e.g. RW access from container.
    env_file:
      - ./app/env_file
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db

  nginx:
    image: "nginx:1.13.8"
    ports:
            #- "8080:80"
      - "8080:443"
    volumes:
      - ./app/conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on:
      - flaskapp

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge

volumes: # can be shared
  dbdata: # purely Postgres
  agotool_data: # version 1
