version: '3'

services:

  db: # name
    image: "postgres:10"
    volumes:
      # named volume, persistent data, lives in special directory from docker
      # created to build Postgres data in it, even if Postgres container is removed Postgres data persists.
       - "dbdata:/var/lib/postgresql/data"

      # named volume. to copy data into with e.g.
      # docker run --rm -it --volume ~/modules/cpr/agotool/data:/mounted_data --volume "agotool_agotool_data:/agotool_data" agotool_flaskapp bash
      # needed to build DB from files (copy from file)
       - "agotool_data:/agotool_data"

      # bind mount to mount files from the host to the container
### Ody
#      - ./data:/agotool_data # bind mounted volume from host, e.g. RW access from container.
### Atlas
#      - /mnt/mnemo5/dblyon/agotool:/agotool_data

    env_file:
      - ./app/env_file
    networks:
      - db_nw

  flaskapp:
    build: . # uncomment to build from Dockerfile, else pull from dockerhub
#    image: dblyon/python_agotool:latest
    volumes:
      # bind mounted volume from host, e.g. RW access from container.
      # use git to push/pull changes. set source to git repo directory e.g. /var/www/agotool on virtual server
### Ody
# local changes are reflected in docker
      - ./app/:/opt/services/flaskapp/src
### Atlas
#      - /mnt/mnemo5/dblyon/agotool/app/:/opt/services/flaskapp/src
### Ody
#       named volume. persistent data container that is managed by docker.
# needed for access to download new resources
      - "agotool_data:/agotool_data"

    env_file:
      - ./app/env_file
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db

  nginx:
    image: "nginx:1.13.8"
    ports:
      - "8080:80"
    volumes:
      - ./app/conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on:
      - flaskapp


networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge


volumes: # can be shared
  dbdata: # purely Postgres
  agotool_data: #
