version: '3'


services:

  db: # name
    image: "postgres:latest"
    volumes:
      - "dbdata:/var/lib/postgresql/data" # named volume, persistent data, lives in special directory from docker
      - "agotool_data:/agotool_data"
      #- ./data:/agotool_data # bind mounted volume from host, e.g. RW access from container.
    env_file:
      - env_file
    networks:
      - db_nw

  flaskapp:
    build: .
    volumes:
      - .:/opt/services/flaskapp/src
      - "agotool_data:/agotool_data"
    env_file:
      - env_file
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db

  nginx:
    image: "nginx:1.13.5"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on:
      - flaskapp


networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge


volumes: # can be shared
  dbdata:
  agotool_data:
