name: agotool
channels:
  - conda-forge
  - anaconda
  - bioconda
  - defaults
dependencies:
  - python=3
  - numpy
  - cython
  - pandas
  - scipy
  - jupyterlab
  - ipython
  - ipykernel
  - libgcc
  - fisher
  - psycopg2
  - line_profiler
  - Werkzeug
  - WTForms
  - Flask
  - flask-restful
  - flask-markdown
  - networkx
  - lxml
  - pytest
  - pytest-cov
  - markdown
  - retrying
  - requests
  - beautifulsoup4
  - uwsgi
#  - pyyaml
#  - uwsgitop # can't be found --> install via pip

### Anaconda installation
# conda remove --name agotool --all
# conda env create -n agotool -f conda_env_agotool.yml
# conda activate agotool