name: snake
channels:
  - conda-forge
  - anaconda
  - defaults
  - bioconda
dependencies:
  - python
  - snakemake
  - numpy
  - scipy
  - pandas
  - cython
  - ipython
  - requests
  - setuptools
  - retrying
  - lxml
  - zlib

### Anaconda installation
# conda remove --name snake --all
# conda env create -n snake -f snakemake_install.yml
# conda activate snake
