# single environment including snakemake
name: agotool
channels:
  - conda-forge
  - anaconda
  - bioconda
  - defaults
dependencies:
  - python=3
  - snakemake
  - cython
  - fisher
  - numpy
  - pandas
  - scipy
  - beautifulsoup4
  - curl
  - flask
  - flask-restful
  - flask-markdown
  - ipdb
  - ipython
  - ipykernel
  - jupyterlab
  - jinja2
  - json5
  - libblas
  - libclang
  - libcurl
  - libgfortran-ng
  - libopenblas
  - libgcc
  - lxml
  - openssl
  - pip
  - psycopg2
  - requests
  - tqdm
  - urllib3
  - Werkzeug
  - WTForms
  - wheel
  - xlrd
  - networkx
  - pytest
  - pytest-cov
  - markdown
  - retrying
  - uwsgi
  - matplotlib
  - seaborn